/*category */
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_SPECIFIC_CATEGORY ="GET_SPECIFIC_CATEGORY"
/*brand */
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const CREATE_BRAND = "CREATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";
export const GET_SPECIFIC_BRAND ="GET_SPECIFIC_BRAND"
/*subCategory */
export const CREATE_SUB_CATEGORY ="CREATE_SUB_CATEGORY"
export const GET_ONE_CATEGORY_SUB ="GET_ONE_CATEGORY_SUB"
/*product */
export const CREATE_PRODUCT ="CREATE_PRODUCT"
export const GET_ALL_PRODUCTS ="GET_ALL_PRODUCTS"
export const GET_ALL_PRODUCTS_BY_CATEGORY ="GET_ALL_PRODUCTS_BY_CATEGORY"
export const GET_ALL_PRODUCTS_BY_CATEGORY_MOBILE ="GET_ALL_PRODUCTS_BY_CATEGORY_MOBILE"
export const GET_ALL_PRODUCTS_BY_CATEGORY_PCCORE ="GET_ALL_PRODUCTS_BY_CATEGORY_PCCORE"
export const GET_ALL_PRODUCTS_BY_CATEGORY_SCHOOL_TOOLS ="GET_ALL_PRODUCTS_BY_CATEGORY_SCHOOL_TOOLS"
export const GET_ALL_PRODUCTS_BY_BRAND ="GET_ALL_PRODUCTS_BY_BRAND"
export const GET_PRODUCT_DETAILS ="GET_PRODUCT_DETAILS"
export const GET_SIMILAR_PRODUCTS = "GET_SIMILAR_PRODUCTS"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
/*user*/
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const GET_CURERNT_USER = "GET_CURERNT_USER"
export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const VERIFY_CODE = "VERIFY_CODE"
export const RESET_PASSWORD = "RESET_PASSWORD"
/*User Reviews*/
export const ADD_REVIEW ="ADD_REVIEW"
export const GET_ALL_REVIEWS ="GET_ALL_REVIEWS"
export const DELETE_REVIEW ="DELETE_REVIEW"
export const UPDATE_REVIEW ="UPDATE_REVIEW"

/*wishlist*/
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST"
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST"

/*coupons*/
export const ADD_COUPON = "ADD_COUPON"
export const DELETE_COUPON = "DELETE_COUPON"
export const UPDATE_COUPON = "UPDATE_COUPON"
export const ALL_COUPONS = "ALL_COUPONS"

//User addresses actions 
export const SPECIFIC_USER = "SPECIFIC_USER"
//Addresses
export const ADD_ADDRESS = "ADD_ADDRESS"
export const DELETE_ADDRESS = "DELETE_ADDRESS"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const GET_ALL_ADDRESSES = "GET_ALL_ADDRESSES"
export const GET_SPECIFIC_ADDRESSES = "GET_SPECIFIC_ADDRESSES"
// User data actions
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const DELETE_USER = "DELETE_USER"
// User update password 
export const UPDATE_USER_PASS = "UPDATE_USER_PASS"
// Cart Actions
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART"
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART"
export const GET_ALL_CART = "GET_ALL_CART"
export const REMOVE_ALL_CART = "REMOVE_ALL_CART"
export const APPLAY_COUPON = "APPLAY_COUPON"
// checkout actions
export const CREATE_ORDER_CASH ="CREATE_ORDER_CASH"
export const CREATE_ORDER_CARD ="CREATE_ORDER_CARD"
// orders actions
export const GET_USER_ORDERS ="GET_USER_ORDERS"
export const GET_SPESIFIC_USER_ORDER ="GET_SPESIFIC_USER_ORDER"
export const UPDATE_ORDER_TO_PAID ="UPDATE_ORDER_TO_PAID"
export const UPDATE_ORDER_TO_DELIVERD ="UPDATE_ORDER_TO_DELIVERD"
// error
export const GET_ERROR = "GET_ERROR";